### ISSUE TITLE
Iniitialize error

### ISSUE THREAD

**Issue by AlexanderOsborne** [turingschool/ruby-exercises#81] opened 2020-09-29 17:30 UTC
When attempting the initialize exercises I was presented with the following error.

```/Users/alexosborne/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/alexosborne/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ./lib/aardvark (LoadError)```

The work around is to cd up a level so that both the library and test directories are below. You can then run the test with the following.

```ruby test/filename.rb```

**Comment by s-espinosa** [comment] 2020-10-30 02:10
Thanks, Alex! Think that’s exactly right. This is the intended behavior, so I wouldn’t consider it an issue, per se. I’m going to go ahead and close this. Please let us know if you think there’s something in the repo that you believe needs to be adjusted.

**Closed by s-espinosa** 2020-10-30 02:10 UTC
